blank_issues_enabled: false
contact_links:
  - name: 💬 Rypî Questions and Discussions
    url: https://discord.com/channels/915183241063960587/915183241646968887
    about: Please ask and answer questions here.
  - name: 💬 Join the Discord community
    url: https://discord.com/channels/915183241063960587/915183241646968887
    about: Come and chat with all the members of the community !
